{
 "title": "pfSense",
 "description": "pfSense dashboard I made for myself that works with basic telegraf installation.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "WAN (em1)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "measurement": "net",
     "query": "SELECT derivative(\"bytes_recv\", 1s) *8 FROM \"net\" WHERE (\"host\" = 'pfSense.nekromanta.pl' AND \"interface\" = 'em1') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "em1" }
     ]
    },
    {
     "alias": "Upload",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "em1" }
     ]
    }
   ]
  },
  {
   "title": "LAN (em0)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "measurement": "net",
     "query": "SELECT derivative(\"bytes_recv\", 1s) *8 FROM \"net\" WHERE (\"host\" = 'pfSense.nekromanta.pl' AND \"interface\" = 'em1') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "em0" }
     ]
    },
    {
     "alias": "Upload",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "em0" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pfSense.nekromanta.pl" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "System",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "Idle",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load 1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load 5",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load 15",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "Free",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Used",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Total",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proccesses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Zombie",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Sleeping",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "sleeping" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Running",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Stopped",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "stopped" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Idle",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Blocked",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unknown",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "unknown" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Diskfree",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Total /tmp",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "md0" }
     ]
    },
    {
     "alias": "Free /tmp",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "md0" }
     ]
    },
    {
     "alias": "Total /var",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "md1" }
     ]
    },
    {
     "alias": "Free /var",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "md1" }
     ]
    },
    {
     "alias": "Total /",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ufs/pfsense1" }
     ]
    },
    {
     "alias": "Free /",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ufs/pfsense1" }
     ]
    },
    {
     "alias": "Total /cf",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ufs/cf" }
     ]
    },
    {
     "alias": "Free /cf",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ufs/cf" }
     ]
    }
   ]
  },
  {
   "title": "PF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Entries",
     "measurement": "pf",
     "select": [
      [
       { "params": [ "entries" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}